version: '3.5'
services:
  goal_api:
    image: goal_account_api
    container_name: goal_account_api_service
    restart: always
    ports:
      - "8100:8100"
    volumes:
      - "./runtime/logs/api:/app/runtime/logs/api"
      - "./settings/compose.json:/app/settings/compose.json"
    command:
      ["./goal", "start", "-c", "settings/compose.json"]

  goal_admin:
    image: goal_account_admin
    container_name: goal_account_admin_service
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - "./runtime/logs/admin:/app/runtime/logs/admin"
      - "./settings/compose.json:/app/settings/compose.json"
    command:
      ["./goal", "start", "-c", "settings/compose.json"]